USB_VID = 0x303A
USB_PID = 0x7003
USB_PRODUCT = "ESP32-P4-Function-EV"
USB_MANUFACTURER = "Espressif"
CIRCUITPY_CREATOR_ID =  0x000C303A
CIRCUITPY_CREATION_ID = 0x0032C003

IDF_TARGET = esp32p4

CIRCUITPY_ESP_FLASH_SIZE = 16MB
CIRCUITPY_ESP_FLASH_MODE = opi
CIRCUITPY_ESP_FLASH_FREQ = 80m

CIRCUITPY_ESP_PSRAM_SIZE = 32MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_TINYUSB = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_USB_CDC = 0 
CIRCUITPY_USB_CDC_CONSOLE_ENABLED_DEFAULT = 0
CIRCUITPY_USB_DEVICE = 0
CIRCUITPY_USB_HID = 0 
CIRCUITPY_USB_HID_ENABLED_DEFAULT = 0
CIRCUITPY_USB_MIDI = 0
CIRCUITPY_USB_MSC = 0
CIRCUITPY_USB_MSC_ENABLED_DEFAULT = 0
CIRCUITPY_PYUSB = 0
CIRCUITPY_USB_KEYBOARD_WORKFLOW = 0
CIRCUITPY_TOUCHIO_USE_NATIVE = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_ESPULP = 0
CIRCUITPY_CANIO = 0
CIRCUITPY_WIFI = 0

CIRCUITPY_HASHLIB=0
CIRCUITPY_HASHLIB_MBEDTLS_ONLY=0
CIRCUITPY_HASHLIB_MBEDTLS = 0
CIRCUITPY_SSL_MBEDTLS = 0

CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_BUSDISPLAY= 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_MAX3421E = 0
CIRCUITPY_SUPERVISOR = 1
CIRCUITPY_KEYPAD = 0
MICROPY_PY_ASYNC_AWAIT = 0
MICROPY_PY_ASYNCIO = 0
CIRCUITPY_STATUS_BAR = 0